---
title: "Schedule"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The second part of the course takes place in the summer semester **Tuesdays 14:00-16:00 CET**.

\

# Provisional Schedule

```{r, echo = FALSE}

library(kableExtra)

dt <- data.frame(schedule = c("1", "2", 
                              "3", "4", 
                              "5", "6",
                              "7", "8",
                              "9", "10", "11", "12", "13"),
                 date = c( "14.04", 
                           "21.04", 
                           "28.04", 
                           "05.05", 
                           "12.05", 
                           "19.05", 
                           "26.05", 
                           "02.06", 
                           "09.06",
                           "16.06",
                           "23.06",
                           "30.06",
                           "07.06"),
                 topics = c("Total-evidence dating", 
                            "Diversification  rate estimation I",
                            "Diversification  rate estimation II",
                            "Introduction to PCMs", 
                            "**No class** (Paul Lewis lectures)", 
                            "**No class** (Paul Lewis lectures)", 
                            "Ancestral state reconstruction",
                            "Biogeography", 
                            "**No class** (Project work)", 
                            "**No class** (Project work)",
                            "Intro to RevBayes",
                            "Model selection and model adequacy",
                            "Project work"
                            ))

names(dt)[1] <- ""

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```

\

# Materials

Course material will be updated here throughout the semester!

## Week 1

```{r, echo = FALSE}

library(kableExtra)

urls <- c("slides/06-FBD-recap.pdf", "https://taming-the-beast.org/tutorials/FBD-tutorial/", "https://taming-the-beast.org/tutorials/Total-Evidence-Tutorial/")

dt <- data.frame(schedule = c("Slides", "Exercise 6", "Exercise 7"),
                 topics = c("Recap", "The FBD process using BEAST2", "Total-evidence dating using BEAST2"))
dt$schedule[1] <- paste0("[", dt$schedule[1], "](", urls[1], ")")
dt$schedule[2] <- paste0("[", dt$schedule[2], "](", urls[2], ")")
dt$schedule[3] <- paste0("[", dt$schedule[3], "](", urls[3], ")")

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```
